# RT-Thread building script for bridge

import os
from building import *

cwd = GetCurrentDir()
src = Glob('*.c')

RLFLASHFS = Split('''
Config/File_Config.c
''')

RLTCPNET = Split('''
Config/Net_Config.c
Config/Net_lib.c
Config/Net_Debug.c
''')

CPPPATH = [cwd + "/RL-RTX/inc"]
CPPPATH += [cwd + "/Config"]
list = os.listdir(cwd)

if GetDepend(['RT_USING_RL_FLASHFS']):
    src += RLFLASHFS
   
if GetDepend(['RT_USING_RL_TCPnet']):
    src += RLTCPNET

group = DefineGroup('RL_ARM', src, depend = ['RT_USING_RL_ARM'], CPPPATH = CPPPATH)

for d in list:
    path = os.path.join(cwd, d)
    if os.path.isfile(os.path.join(path, 'SConscript')):
        group = group + SConscript(os.path.join(d, 'SConscript'))

Return('group')