# RT-Thread building script for component

from building import *

cwd = GetCurrentDir()

src = Glob('*.c')
LIBPATH = [cwd + '/lib']

NANDFLASH = Split('''
src/FS_NAND_FlashPrg.c

''')

MICROSD = Split('''
src/FS_MicroSD_Cardprg.c

''')

src = src + NANDFLASH

if GetDepend(['BSP_USING_TFCARD']):
    src += MICROSD

LIBS = ['FSN_CM3']
 
CPPPATH = [cwd, cwd + '/inc']

group = DefineGroup('RLFlashFS', src , depend = ['RT_USING_RL_ARM', 'RT_USING_RL_FLASHFS'], CPPPATH = CPPPATH,LIBS = LIBS, LIBPATH=LIBPATH)

Return('group')
