# RT-Thread building script for component

from building import *

cwd = GetCurrentDir()
src = Split('''
FTP_uif.c
''')
LIBPATH = [cwd + '/lib']

LIBS = ['TCPD_CM3']
 
group = DefineGroup('RLTCPnet', src,depend = ['RT_USING_RL_ARM', 'RT_USING_RL_TCPnet'],LIBS = LIBS, LIBPATH=LIBPATH)

Return('group')
