# RT-Thread building script for component

from building import *

cwd = GetCurrentDir()
src = Glob('*.c')

CPPPATH = [cwd]

group = DefineGroup('gui', src, depend = ['RT_USING_NANOGUI'], CPPPATH = CPPPATH)

Return('group')
